### ISSUE TITLE
Minor issue with the type-hint of $userId in VerifyEmailHelperInterface

### ISSUE THREAD

**Issue by Yondz** [SymfonyCasts/verify-email-bundle#46]
Hey there,

I've just started using this bundle combined with the helpers from MakerBundle (really great, thanks ! Save me some time and troubles !) and noticed a weird type-hint issue when using `declare(strict_types=1);` related to `string $userId` type hints into `VerifyEmailHelperInterface` : 

```php
    /**
     * @param string $userId unique user identifier
     */
    public function generateSignature(string $routeName, string $userId, string $userEmail, array $extraParams = []): VerifyEmailSignatureComponents;

    /**
     * @param string $userId currently-authenticated user's unique identifier
     */
    public function validateEmailConfirmation(string $signedUrl, string $userId, string $userEmail): void;
```

Indeed, the default behavior using MakerBundle is to supply `$user->getId()` for these arguments, and thus, `int|null` in most of the cases, whereas `$userId` is typed as string.

Maybe this would be better to not type it for now ? Anyway It is still possible for developers to avoid this by casting or else at the Controller level, so that is not a critical issue.

See ya :)

**Comment by jrushlow** [comment]
Hi @Yondz , thanks for the feedback! I think it's in the best interest of the bundle to not remove the type hint. Primarily because changing signatures in the interface could have undesired consequences for existing users of the bundle. Secondly, PHP as a whole is becoming more of a typed language - which is a good thing in my opinion. If `$userId` was not typed, we would have to do extra work within the bundle it self to make sure someone was not passing a `bool` as the id. 

Anyhow, with our types as is, this enforces the fact the we need a `string` for the `$userId` without extra work.

**Comment by Yondz** [comment]
Hi @jrushlow,

I agree :) 

Maybe this should be taken care on MakerBundle side in fact (it's MakerBundle that uses the interface in a non-strict way without any type casting : https://github.com/symfony/maker-bundle/blob/main/src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php#L30 and https://github.com/symfony/maker-bundle/blob/main/src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php#L49)
