### ISSUE TITLE
Suggestion: full customize signed URL

### ISSUE THREAD

**Issue by ph1823** [SymfonyCasts/verify-email-bundle#64]
Hello ! So there you have it, before using a homemade system, from time and md5. But I decided to switch to your bundle for more security.
So I tried to customize my validation URL as I had before by adapting to your bundle.
But impossible to remove the "? Token = ..", "? Signature = ..", "? Expire = .." which is not very aesthetic, I would like a URL in the form / confirm-mail / {token} / {signature} / {expires}

I make this suggestion, because by viewing the documentation as well as the bundle code I am not sure that it is compatible with the form of url to ask.
If it's compatible, tell me and close this issue,
Thank you for taking the time to read my suggestion

**Comment by weaverryan** [comment]
Hi @ph1823!

I think what you want is *almost* possible :). We can definitely generate something like `/confirm-mail/{token}/{expires}?signature=`. So, everything except for the signature. That's just, unfortunately, due to how the URL is "signed": we need to generate the URL first, and then add the signature via a query param.

If this is "good enough" for you, the only trick is to make sure that your `registration_confirmation_route` (or whatever you pass as the 1st arg to the `generateSignature()` method) has `{token}` and `{expiration}` wildcards.

Let me know what you think.

Cheers!

**Comment by ph1823** [comment]
Hello, it actually works! Too bad we can't include the? Signature in our base URL, maybe that will be possible in the future!

I just thought about it after several days, but the best way would be to redirect the user directly after the url, so that the user will only see the mail very little, and it would be less complicated to do

Thank you for your help,
Cheers !
